version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:80"
    volumes:
      - linkup-data:/app/data
    networks:
      - app-network

volumes:
  linkup-data:

networks:
  app-network:
    driver: bridge
