services:
  client:
    build: ./client
    ports:
      - "4200:80"
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  api:
    build: ./API
    ports:
      - "5000:80"
    volumes:
      - ./API/data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80