services:
  client:
    build: ./client
    ports:
      - "4200:80"
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  api:
    build: ./API
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=TestDB;Username=postgres;Password=12345
  db:
    image: postgres:15
    restart: always
    environment:

      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: TestDB
    ports:
      - "5432:5432"
    volumes:
      - db-data-named:/var/lib/postgresql/data # This refers to the named volume defined below
volumes:
  db-data-named:
    
